/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Example
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateTodoDto,
  DeleteTodoDto,
  GetTodoDto,
  UpdateTodoDto
} from './model';

export type appControllerGetHelloResponse200 = {
  data: void
  status: 200
}
    
export type appControllerGetHelloResponseSuccess = (appControllerGetHelloResponse200) & {
  headers: Headers;
};
;

export type appControllerGetHelloResponse = (appControllerGetHelloResponseSuccess)

export const getAppControllerGetHelloUrl = () => {


  

  return `http://localhost:4000/api`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<appControllerGetHelloResponse> => {
  
  const res = await fetch(getAppControllerGetHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: appControllerGetHelloResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetHelloResponse
}



export type todoControllerGetTodoResponse200 = {
  data: GetTodoDto[]
  status: 200
}
    
export type todoControllerGetTodoResponseSuccess = (todoControllerGetTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerGetTodoResponse = (todoControllerGetTodoResponseSuccess)

export const getTodoControllerGetTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerGetTodo = async ( options?: RequestInit): Promise<todoControllerGetTodoResponse> => {
  
  const res = await fetch(getTodoControllerGetTodoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerGetTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerGetTodoResponse
}



export type todoControllerPostTodoResponse200 = {
  data: CreateTodoDto
  status: 200
}
    
export type todoControllerPostTodoResponseSuccess = (todoControllerPostTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerPostTodoResponse = (todoControllerPostTodoResponseSuccess)

export const getTodoControllerPostTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerPostTodo = async (createTodoDto: CreateTodoDto, options?: RequestInit): Promise<todoControllerPostTodoResponse> => {
  
  const res = await fetch(getTodoControllerPostTodoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTodoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerPostTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerPostTodoResponse
}



export type todoControllerPutTodoResponse200 = {
  data: UpdateTodoDto
  status: 200
}
    
export type todoControllerPutTodoResponseSuccess = (todoControllerPutTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerPutTodoResponse = (todoControllerPutTodoResponseSuccess)

export const getTodoControllerPutTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerPutTodo = async (updateTodoDto: UpdateTodoDto, options?: RequestInit): Promise<todoControllerPutTodoResponse> => {
  
  const res = await fetch(getTodoControllerPutTodoUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTodoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerPutTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerPutTodoResponse
}



export type todoControllerDeleteTodoResponse200 = {
  data: DeleteTodoDto
  status: 200
}
    
export type todoControllerDeleteTodoResponseSuccess = (todoControllerDeleteTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerDeleteTodoResponse = (todoControllerDeleteTodoResponseSuccess)

export const getTodoControllerDeleteTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerDeleteTodo = async (deleteTodoDto: DeleteTodoDto, options?: RequestInit): Promise<todoControllerDeleteTodoResponse> => {
  
  const res = await fetch(getTodoControllerDeleteTodoUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteTodoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerDeleteTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerDeleteTodoResponse
}


export const getTodoControllerGetTodoResponseMock = (): GetTodoDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), complete: faker.datatype.boolean(), title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getTodoControllerPostTodoResponseMock = (overrideResponse: Partial< CreateTodoDto > = {}): CreateTodoDto => ({title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getTodoControllerPutTodoResponseMock = (overrideResponse: Partial< UpdateTodoDto > = {}): UpdateTodoDto => ({id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), complete: faker.datatype.boolean(), ...overrideResponse})

export const getTodoControllerDeleteTodoResponseMock = (overrideResponse: Partial< DeleteTodoDto > = {}): DeleteTodoDto => ({id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getAppControllerGetHelloMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getTodoControllerGetTodoMockHandler = (overrideResponse?: GetTodoDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTodoDto[]> | GetTodoDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerGetTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTodoControllerPostTodoMockHandler = (overrideResponse?: CreateTodoDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateTodoDto> | CreateTodoDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerPostTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTodoControllerPutTodoMockHandler = (overrideResponse?: UpdateTodoDto | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateTodoDto> | UpdateTodoDto), options?: RequestHandlerOptions) => {
  return http.put('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerPutTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTodoControllerDeleteTodoMockHandler = (overrideResponse?: DeleteTodoDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteTodoDto> | DeleteTodoDto), options?: RequestHandlerOptions) => {
  return http.delete('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerDeleteTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getExampleMock = () => [
  getAppControllerGetHelloMockHandler(),
  getTodoControllerGetTodoMockHandler(),
  getTodoControllerPostTodoMockHandler(),
  getTodoControllerPutTodoMockHandler(),
  getTodoControllerDeleteTodoMockHandler()
]
