/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Example
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateTodoDto,
  DeleteTodoDto,
  UpdateTodoDto
} from './model';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GetTodoDto
} from './model';

export type appControllerGetHelloResponse200 = {
  data: void
  status: 200
}
    
export type appControllerGetHelloResponseSuccess = (appControllerGetHelloResponse200) & {
  headers: Headers;
};
;

export type appControllerGetHelloResponse = (appControllerGetHelloResponseSuccess)

export const getAppControllerGetHelloUrl = () => {


  

  return `http://localhost:4000/api`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<appControllerGetHelloResponse> => {
  
  const res = await fetch(getAppControllerGetHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: appControllerGetHelloResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetHelloResponse
}




export const getAppControllerGetHelloKey = () => [`http://localhost:4000/api`] as const;

export type AppControllerGetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>

export const useAppControllerGetHello = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof appControllerGetHello>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getAppControllerGetHelloKey() : null);
  const swrFn = () => appControllerGetHello(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type todoControllerGetTodoResponse200 = {
  data: GetTodoDto[]
  status: 200
}
    
export type todoControllerGetTodoResponseSuccess = (todoControllerGetTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerGetTodoResponse = (todoControllerGetTodoResponseSuccess)

export const getTodoControllerGetTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerGetTodo = async ( options?: RequestInit): Promise<todoControllerGetTodoResponse> => {
  
  const res = await fetch(getTodoControllerGetTodoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerGetTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerGetTodoResponse
}




export const getTodoControllerGetTodoKey = () => [`http://localhost:4000/api/todo`] as const;

export type TodoControllerGetTodoQueryResult = NonNullable<Awaited<ReturnType<typeof todoControllerGetTodo>>>

export const useTodoControllerGetTodo = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof todoControllerGetTodo>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getTodoControllerGetTodoKey() : null);
  const swrFn = () => todoControllerGetTodo(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type todoControllerPostTodoResponse201 = {
  data: GetTodoDto
  status: 201
}
    
export type todoControllerPostTodoResponseSuccess = (todoControllerPostTodoResponse201) & {
  headers: Headers;
};
;

export type todoControllerPostTodoResponse = (todoControllerPostTodoResponseSuccess)

export const getTodoControllerPostTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerPostTodo = async (createTodoDto: CreateTodoDto, options?: RequestInit): Promise<todoControllerPostTodoResponse> => {
  
  const res = await fetch(getTodoControllerPostTodoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTodoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerPostTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerPostTodoResponse
}




export const getTodoControllerPostTodoMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateTodoDto }) => {
    return todoControllerPostTodo(arg, options);
  }
}
export const getTodoControllerPostTodoMutationKey = () => [`http://localhost:4000/api/todo`] as const;

export type TodoControllerPostTodoMutationResult = NonNullable<Awaited<ReturnType<typeof todoControllerPostTodo>>>

export const useTodoControllerPostTodo = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof todoControllerPostTodo>>, TError, Key, CreateTodoDto, Awaited<ReturnType<typeof todoControllerPostTodo>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getTodoControllerPostTodoMutationKey();
  const swrFn = getTodoControllerPostTodoMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type todoControllerPutTodoResponse200 = {
  data: GetTodoDto
  status: 200
}
    
export type todoControllerPutTodoResponseSuccess = (todoControllerPutTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerPutTodoResponse = (todoControllerPutTodoResponseSuccess)

export const getTodoControllerPutTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerPutTodo = async (updateTodoDto: UpdateTodoDto, options?: RequestInit): Promise<todoControllerPutTodoResponse> => {
  
  const res = await fetch(getTodoControllerPutTodoUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTodoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerPutTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerPutTodoResponse
}




export const getTodoControllerPutTodoMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateTodoDto }) => {
    return todoControllerPutTodo(arg, options);
  }
}
export const getTodoControllerPutTodoMutationKey = () => [`http://localhost:4000/api/todo`] as const;

export type TodoControllerPutTodoMutationResult = NonNullable<Awaited<ReturnType<typeof todoControllerPutTodo>>>

export const useTodoControllerPutTodo = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof todoControllerPutTodo>>, TError, Key, UpdateTodoDto, Awaited<ReturnType<typeof todoControllerPutTodo>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getTodoControllerPutTodoMutationKey();
  const swrFn = getTodoControllerPutTodoMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type todoControllerDeleteTodoResponse200 = {
  data: GetTodoDto
  status: 200
}
    
export type todoControllerDeleteTodoResponseSuccess = (todoControllerDeleteTodoResponse200) & {
  headers: Headers;
};
;

export type todoControllerDeleteTodoResponse = (todoControllerDeleteTodoResponseSuccess)

export const getTodoControllerDeleteTodoUrl = () => {


  

  return `http://localhost:4000/api/todo`
}

export const todoControllerDeleteTodo = async (deleteTodoDto: DeleteTodoDto, options?: RequestInit): Promise<todoControllerDeleteTodoResponse> => {
  
  const res = await fetch(getTodoControllerDeleteTodoUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteTodoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: todoControllerDeleteTodoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as todoControllerDeleteTodoResponse
}




export const getTodoControllerDeleteTodoMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: DeleteTodoDto }) => {
    return todoControllerDeleteTodo(arg, options);
  }
}
export const getTodoControllerDeleteTodoMutationKey = () => [`http://localhost:4000/api/todo`] as const;

export type TodoControllerDeleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof todoControllerDeleteTodo>>>

export const useTodoControllerDeleteTodo = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof todoControllerDeleteTodo>>, TError, Key, DeleteTodoDto, Awaited<ReturnType<typeof todoControllerDeleteTodo>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getTodoControllerDeleteTodoMutationKey();
  const swrFn = getTodoControllerDeleteTodoMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}


export const getTodoControllerGetTodoResponseMock = (): GetTodoDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), complete: faker.datatype.boolean(), title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getTodoControllerPostTodoResponseMock = (overrideResponse: Partial< GetTodoDto > = {}): GetTodoDto => ({id: faker.string.alpha({length: {min: 10, max: 20}}), complete: faker.datatype.boolean(), title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTodoControllerPutTodoResponseMock = (overrideResponse: Partial< GetTodoDto > = {}): GetTodoDto => ({id: faker.string.alpha({length: {min: 10, max: 20}}), complete: faker.datatype.boolean(), title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTodoControllerDeleteTodoResponseMock = (overrideResponse: Partial< GetTodoDto > = {}): GetTodoDto => ({id: faker.string.alpha({length: {min: 10, max: 20}}), complete: faker.datatype.boolean(), title: faker.string.alpha({length: {min: 10, max: 20}}), comment: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getAppControllerGetHelloMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getTodoControllerGetTodoMockHandler = (overrideResponse?: GetTodoDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTodoDto[]> | GetTodoDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerGetTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTodoControllerPostTodoMockHandler = (overrideResponse?: GetTodoDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GetTodoDto> | GetTodoDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerPostTodoResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTodoControllerPutTodoMockHandler = (overrideResponse?: GetTodoDto | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<GetTodoDto> | GetTodoDto), options?: RequestHandlerOptions) => {
  return http.put('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerPutTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTodoControllerDeleteTodoMockHandler = (overrideResponse?: GetTodoDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<GetTodoDto> | GetTodoDto), options?: RequestHandlerOptions) => {
  return http.delete('*/api/todo', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTodoControllerDeleteTodoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getExampleMock = () => [
  getAppControllerGetHelloMockHandler(),
  getTodoControllerGetTodoMockHandler(),
  getTodoControllerPostTodoMockHandler(),
  getTodoControllerPutTodoMockHandler(),
  getTodoControllerDeleteTodoMockHandler()
]
