apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
requireApproval: false
run:
  location: projects/yonezawa-sandbox/locations/asia-northeast1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-target
requireApproval: false
run:
  location: projects/yonezawa-sandbox/locations/asia-northeast1
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: test-pipeline
serialPipeline:
  stages:
    - targetId: dev-target
      profiles: [dev]
      # strategy:
      #   canary:
      #     runtimeConfig:
      #       cloudRun:
      #         automaticTrafficControl: true
      #     canaryDeployment:
      #       percentages: [25, 50, 75]
    - targetId: prod-target
      profiles: [prod]
      strategy:
        # # standard:
        # #   verify: true
        # canary:
        #   runtimeConfig:
        #     cloudRun:
        #       automaticTrafficControl: true
        #   canaryDeployment:
        #     percentages: [25, 50, 75]
