apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service-dev
  annotations:
    run.googleapis.com/binary-authorization: default
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: docker.io/httpd
          ports:
            - name: http1
              containerPort: 80
          startupProbe:
            tcpSocket:
              port: 80
