apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: deploy-run-
profiles:
  - name: dev
    manifests:
      rawYaml:
        - run-service-dev.yaml
  - name: prod
    manifests:
      rawYaml:
        - run-service-prod.yaml
deploy:
  cloudrun: {}
verify:
  - name: after-deploy-verification
    container:
      name: alpine-wget
      image: alpine:latest
      command: ["/bin/sh"]
      args: ["-c", "wget https://google.com"]
