/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Example
 * The cats API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateTodoDto {
  id: string;
  title: string;
  comment: string;
  complete: boolean;
}
